// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/desktop/code/backend-project/star-project/landada/landada-frontend/src/models/app';
import model_2 from 'D:/desktop/code/backend-project/star-project/landada/landada-frontend/src/models/user';
import model_3 from 'D:/desktop/code/backend-project/star-project/landada/landada-frontend/src/.umi/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'app', model: model_1 },
model_2: { namespace: 'user', model: model_2 },
model_3: { namespace: '@@initialState', model: model_3 },
} as const
